version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kv-task
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_HOST=db
      - POSTGRES_HOST_AUTH_METHOD=trust
  api:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - SECRET_KEY=10fi8hw98dhfvw987erfhw-e98fjwdpe
    ports:
      - "8000:8000"
    depends_on:
      - db